lsi: false

# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year-:month-:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
excerpt_separator: "<!--break-->"

paginate: 10

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : CRySoL
tagline: Ciudad Real y Software Libre
author :
  name : CRySoL
  email : crysol@gmail.com
  github : CRySoL
#  twitter : username
#  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://CRySoL.github.io

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex:
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : crysol
#    livefyre :
#      site_id : 123
#    intensedebate :
#      account : 123abc
#    facebook :
#      appid : 123
#      num_posts: 5
#      width: 580
#      colorscheme: light

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : google
    google :
        tracking_id : 'UA-41670065-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : tweet

  # Settings for all other include helpers can be defined by creating
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

category_icons:
  cooking:    http://crysol.org/files/category_pictures/cocina.png

tag_icons:
  Arco:         http://crysol.org/files/category_pictures/arco_3D_taxonomy.png
  Python:       http://crysol.org/files/category_pictures/python.png
  android:      http://crysol.org/files/category_pictures/android.png
  blender:      http://crysol.org/files/category_pictures/blender.png
  ceslcam:      http://crysol.org/files/category_pictures/ceslcam.png
  chumby:       http://crysol.org/files/category_pictures/chumby.png
  debian-devel: http://crysol.org/files/category_pictures/debian-devel.png
  debian:       http://crysol.org/files/category_pictures/debian.png
  emacs:        http://crysol.org/files/category_pictures/emacs.png
  embedded:     http://crysol.org/files/category_pictures/embedded.png
  git:          http://crysol.org/files/category_pictures/git.png
  gnome:        http://crysol.org/files/category_pictures/gnome.png
  gstreamer:    http://crysol.org/files/category_pictures/gstreamer.png
  gtk:          http://crysol.org/files/category_pictures/gtk2.png
  hurd:         http://crysol.org/files/category_pictures/hurd.png
  ice:          http://crysol.org/files/category_pictures/zeroc_logo.png
  ingsoft:      http://crysol.org/files/category_pictures/ingsoft.png
  jdk:          http://crysol.org/files/category_pictures/openjdk.png
  latex:        http://crysol.org/files/category_pictures/LaTeX_logo.png
  linux:        http://crysol.org/files/category_pictures/linux.png
  mercurial:    http://crysol.org/files/category_pictures/hg.png
  molinux:      http://crysol.org/files/category_pictures/molinux.png
  nds:          http://crysol.org/files/category_pictures/nds_gnu.png
  networking:   http://crysol.org/files/category_pictures/networking.png
  oreto:        http://crysol.org/files/category_pictures/oreto.gif
  platanada:    http://crysol.org/files/category_pictures/platanada.png
  proselitism:  http://crysol.org/files/category_pictures/ignucious.png
  security:     http://crysol.org/files/category_pictures/seguridad_taxonomy.png
  shell:        http://crysol.org/files/category_pictures/shell.png
  jekyll:       http://jekyllrb.com/img/logo-2x.png

authors:
  admin:
    name: admin
    nick: admin
    email: david.villa@gmail.com
    picture: files/pictures/picture-1.png
  david_villa:
    name: David Villa
    nick: david.villa
    email: david.villa@gmail.com
    twitter: david_vi11a
    github: davidvilla
    bitbucket: DavidVilla
    gravatar: 41aae9eabb1ef8e1cb8ab5619af82083
  magmax:
    gravatar: bb867552994775eb5b94525142c5f6e3
    name: magmax
    nick: magmax
    email: miguelangel.garcia@gmail.com
    picture: files/pictures/picture-2.png
  felix:
    name: felix
    nick: felix
    email: felix.villanueva@uclm.es
  arturo:
    name: arturo
    nick: arturo
    email: arturoj.gomez@gmail.com
    picture: files/pictures/picture-6.jpg
  diego:
    gravatar: 3eb93ae928dc8d17c13a82b3f80b1f0a
    name: diego
    nick: diego
    email: diegomartinsf@gmail.com
    picture: files/pictures/picture-7.png
  int-0:
    name: int-0
    nick: int-0
    email: tobias.diaz@alu.uclm.es
    picture: files/pictures/picture-8.jpg
  Ismael_Caballero:
    name: Ismael.Caballero
    nick: Ismael.Caballero
    email: Ismael.Caballero@uclm.es
  nacho:
    name: nacho
    nick: nacho
    email: ignacio.diez.arias@gmail.es
    picture: files/pictures/picture-13.gif
  javieralso:
    gravatar: 224f22eebba5a0b9381242cda877fbcc
    name: javieralso
    nick: javieralso
    email: javieralso@gmail.com
  cleto:
    gravatar: 0ffa4586a8c06cdcafd7d39b4f37a30c
    name: cleto
    nick: cleto
    email: cleto.martin@gmail.com
    picture: files/pictures/picture-17.png
  fsancho:
    gravatar: 9fdbce59b2a9a983ec4e9cedc44e51af
    name: fsancho
    nick: fsancho
    email: toptnc@gmail.com
    picture: files/pictures/picture-19.gif
  Geronimo:
    gravatar: fb6b7357477c2879509281d8f2337763
    name: Geronimo
    nick: Geronimo
    email: davidcaste@gmail.com
    picture: files/pictures/picture-20.jpg
  KO_mOd_O:
    name: KO_mOd_O
    nick: KO_mOd_O
    email: DVallejoFernandez@gmail.com
  ricardo:
    name: ricardo
    nick: ricardo
    email: ricardo822000@yahoo.es
  jota:
    name: jota
    nick: jota
    email: jj.pufa@gmail.com
  Lk2:
    gravatar: 9acfe8072492b88d5153553244bee99d
    name: Lk2
    nick: Lk2
    email: josel.segura@gmx.es
    picture: files/pictures/picture-26.jpg
  tato:
    gravatar: dfc342a137547a49f5942785bb8f436d
    name: tato
    nick: tato
    email: bamedibaal@gmail.com
    picture: files/pictures/picture-28.jpg
  CRySoL:
    name: CRySoL
    nick: CRySoL
    email: razyel@gmx.net
  ixmith:
    name: ixmith
    nick: ixmith
    email: ixmith@gmail.com
  gloria:
    gravatar: ced649b037f10953a291de074087fbaa
    name: gloria
    nick: gloria
    email: globargon@gmail.com
    picture: files/pictures/picture-45.jpg
  ritxi:
    name: ritxi
    nick: ritxi
    email: ritxi666@hotmail.com
  loren:
    name: loren
    nick: loren
    email: lorenzo.lopez@gmail.com
  ljimenez:
    name: ljimenez
    nick: ljimenez
    email: luis.jimenez@uclm.es
  sqater07:
    name: sqater07
    nick: sqater07
    email: quijote.crysol@quijote.nom.es
  Consegliere:
    name: Consegliere
    nick: Consegliere
    email: ppalazon@member.fsf.org
  Seth:
    gravatar: 46dc354a1f66f5efcfe5b9fd92eb7f77
    name: Seth
    nick: Seth
    email: fnez666@gmail.com
  aledelgal:
    name: aledelgal
    nick: aledelgal
    email: aledelgal@gmail.com
  brue:
    gravatar: aac4252291c3d7988a91cd89c4e07fd9
    name: brue
    nick: brue
    email: djbrue@gmail.com
    picture: files/pictures/picture-99.gif
  matisnow:
    name: matisnow
    nick: matisnow
    email: snow_@hotmail.com
  Heracles:
    name: Heracles
    nick: Heracles
    email: manuelj.abaldea@alu.uclm.es
    picture: files/pictures/picture-110.jpg
  oscarah:
    name: oscarah
    nick: oscarah
    email: oscar.acena@gmail.com
    picture: files/pictures/picture-111.gif
  fernando:
    name: fernando
    nick: fernando
    email: fernando.rincon@uclm.es
  zarco:
    name: zarco
    nick: zarco
    email: Javier.Zarco1@alu.uclm.es
  fmreja:
    name: fmreja
    nick: fmreja
    email: fmreja@fmreja.jazztel.es
  morcy:
    gravatar: 38d92dd1e1b94d2ca148df74464cd5bd
    name: morcy
    nick: morcy
    email: carlos.gonzalez@uclm.es
    picture: files/pictures/picture-128.jpg
  gnumac:
    name: gnumac
    nick: gnumac
    email: steve.jobs@hotmail.com
  bati:
    name: bati
    nick: bati
    email: juanbddc@yahoo.es
  paco:
    name: paco
    nick: paco
    email: Francisco.Moya@uclm.es
  DarioAxel:
    name: DarioAxel
    nick: DarioAxel
    email: darioaxel@gmail.com
  kronox:
    name: kronox
    nick: kronox
    email: linux@linux-gnu.com
  goyo:
    name: goyo
    nick: goyo
    email: goyocasero@gmail.com
  Marset:
    name: Marset
    nick: Marset
    email: fernando@marset.org
  kat_chme:
    name: kat_chme
    nick: kat_chme
    email: zishika@gmail.com
  toledanus:
    name: toledanus
    nick: toledanus
    email: toledanus@gmail.com
  noe:
    name: noe
    nick: noe
    email: lunoes@hotmail.com
  ceslcam:
    name: ceslcam
    nick: ceslcam
    email: pablo.delpozo@ceslcam.com
  carlos_santana:
    name: carlos_santana
    nick: carlos_santana
    email: carlos@inmobiliaria.org
  fidel:
    name: fidel
    nick: fidel
    email: fidel65m@hotmail.com
  manueldavid:
    name: manueldavid
    nick: manueldavid
    email: manueldavid83@hotmail.com
    picture: files/pictures/picture-531.png
  lsc_adriana:
    name: lsc_adriana
    nick: lsc_adriana
    email: cielo_aj@hotmail.com
  jsarthou:
    name: jsarthou
    nick: jsarthou
    email: sarthou@gmail.com
  Victor:
    name: Victor
    nick: Victor
    email: volmo84@gmail.com
  jalbusac:
    name: jalbusac
    nick: jalbusac
    email: jalbusac@gmail.com
  fcojavierc25:
    gravatar: 989108036fc1073a68e700bdb74f7468
    name: fcojavierc25
    nick: fcojavierc25
    email: fcojavierc25@hotmail.com
    picture: files/pictures/picture-698.gif
  kryle:
    name: kryle
    nick: kryle
    email: kryle_08@hotmail.com
  raul:
    name: raul
    nick: raul
    email: cartermena@hotmail.com
  LaEspiral:
    name: LaEspiral
    nick: LaEspiral
    email: lala@lala.com
  Vigilante:
    name: Vigilante
    nick: Vigilante
    email: javierperis@gmail.com
    picture: files/pictures/picture-805.jpg
  darkgnu:
    name: darkgnu
    nick: darkgnu
    email: dark_gnu@yahoo.es
    picture: files/pictures/picture-817.png
  Melef:
    name: Melef
    nick: Melef
    email: melefdefanelia@hotmail.com
  arkangel:
    gravatar: fa3256160ee376daf1658ad069d51c0e
    name: arkangel
    nick: arkangel
    email: arkangel.cl@gmail.com
  rek2:
    gravatar: 1a8792d5f52552dff9cd287a32a5d9a7
    name: rek2
    nick: rek2
    email: rek2@binaryfreedom.info
  josefern:
    name: josefern
    nick: josefern
    email: jf_moya@hotmail.com
    picture: files/pictures/picture-840.jpg
  mjsantof:
    name: mjsantof
    nick: mjsantof
    email: MariaJose.Santofimia@uclm.es
    picture: files/pictures/picture-1292.jpg
  ottoreuss:
    gravatar: b5ca848ee051cafcba6062f23bcefd5f
    name: ottoreuss
    nick: ottoreuss
    email: ottoreuss@hotmail.com
    picture: files/pictures/picture-1325.jpg
  almudena:
    name: almudena
    nick: almudena
    email: almudena.ballester@gmail.com
  nachxs:
    name: nachxs
    nick: nachxs
    email: nachxs@gmail.com
  ns2:
    name: ns2
    nick: ns2
    email: JMMG82@yahoo.es
  RMerchan:
    name: RMerchan
    nick: RMerchan
    email: rmerchan@infoglobal.es
  jorgeroden:
    name: jorgeroden
    nick: jorgeroden
    email: jorgeroden@gmail.com
  electrolinux:
    name: electrolinux
    nick: electrolinux
    email: ralbab@gmail.com
  Yeshua:
    name: Yeshua
    nick: Yeshua
    email: dates9979@yahoo.es
  Salsicha:
    name: Salsicha
    nick: Salsicha
    email: paracosas@hotmail.com
  shakaran:
    gravatar: e705b40159e5ad11fcbc25776403e1cb
    name: shakaran
    nick: shakaran
    email: shakaran@gmail.com
    picture: files/pictures/picture-2054.png
  webtraviesa:
    name: webtraviesa
    nick: webtraviesa
    email: bsegura@redaccenir.com
  wmosquera:
    name: wmosquera
    nick: wmosquera
    email: wmosquera@tecnoav.com
  luis_munoz:
    name: luis.munoz
    nick: luis.munoz
    email: luis.munoz.villarreal@gmail.com
  greenbite:
    gravatar: 36caaedd3491d79279b2c7a6b06e1e2f
    name: greenbite
    nick: greenbite
    email: greenbite@gmail.com
    picture: files/pictures/picture-2004.jpg
  Elpaco:
    name: Elpaco
    nick: Elpaco
    email: fernandoortola@wanadoo.nl
    picture: files/pictures/picture-1990.jpg
  wintux:
    name: wintux
    nick: wintux
    email: australbit@yahoo.es
    picture: files/pictures/picture-2051.jpg
  Matstella:
    name: Matstella
    nick: Matstella
    email: marstella69@hotmail.com
  david_garcia:
    name: david.garcia
    nick: david.garcia
    email: dave.alcarin@gmail.com
  suso:
    name: suso
    nick: suso
    email: smc@manticore.es
  icaro:
    name: icaro
    nick: icaro
    email: karpvs@yahoo.fr
  inakin:
    name: inakin
    nick: inakin
    email: ignacio.arriaga@gmail.com
  john:
    name: john
    nick: john
    email: john.reveco@gmail.com
  jorge:
    name: jorge
    nick: jorge
    email: jorge.barco@alu.uclm.es
  epatipati:
    name: epatipati
    nick: epatipati
    email: epatipati@gmail.com
  morbius:
    name: morbius
    nick: morbius
    email: lothard@hotmail.com
  Tanganas:
    gravatar: d114e7397451ed24030368f80b6dd723
    name: Tanganas
    nick: Tanganas
    email: heracles777@gmail.com
    picture: files/pictures/picture-3017.jpg
  technomasterhack:
    gravatar: 039496f0fb43983b9ecc5a31707318d5
    name: technomasterhack
    nick: technomasterhack
    email: principecontrahecho@hotmail.com
  Trini:
    name: Trini
    nick: Trini
    email: trini86.quintana@gmail.com
  Marot77:
    name: Marot77
    nick: Marot77
    email: contacto@pablomaroto.es
    picture: files/pictures/picture-3331.jpg
  netup:
    name: netup
    nick: netup
    email: vans2k@gmail.com
    picture: files/pictures/picture-2967.png
  squiralte1:
    name: squiralte1
    nick: squiralte1
    email: squiralte1@gmail.com
    picture: files/pictures/picture-3330.gif
  michurin:
    name: michurin
    nick: michurin
    email: alexey@michurin.com.ru
  esteban_trabajos:
    name: esteban_trabajos
    nick: esteban_trabajos
    email: esteban.trabajitos@gmail.com
  hornbas863:
    name: hornbas863
    nick: hornbas863
    email: re.edreenogh@gmail.com
  psm1984:
    name: psm1984
    nick: psm1984
    email: psm1984@gmail.com
  animesfl:
    name: animesfl
    nick: animesfl
    email: animesflawliet@hotmail.com
  RRC19189:
    name: RRC19189
    nick: RRC19189
    email: RRC19189@Gmail.com
    picture: files/pictures/picture-3642.jpg
