name: Jekyll automatic build
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: compile jekyll site
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Madrid

    - name: login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/source:/srv/jekyll \
        docker.pkg.github.com/crysol/crysol.github.io/jekyll-and-deps:3.8 \
        /bin/bash -c "chmod o+rw -R /srv/jekyll && jekyll build --trace -b crysol.org"
        
    - name: commit result
      run: |
        cp -r source/_site/* .
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "github action jekyll build"
        git push


