name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/jekyll:3.8 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --trace"
        
    - name: commit _site
      run: |
        git add _site/*
        git commit -a -m "github action jekyll build"
