name: Jekyll automatic build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/jekyll:3.8 \
        /bin/bash -c "chmod o+rw -R /srv/jekyll && jekyll build --trace -d docs -b crysol.org"
        
    - name: commit result
      run: |
        git config --local user.email "david.villa@gmail.com"
        git config --local user.name "David Villa Alises"
        git commit -a -m "github action jekyll build"
        git push

